version: "3.8"
services:
  
  socialnetwork_env:
    container_name: socialnetwork_env
    image: ${DOCKER_REPO}/socialnetworkenv
    network_mode: host
    build:
      context: ../../
      dockerfile: cicd/docker/snEnvironment
    tty: true
  
  socialnetwork_setup:
    container_name: socialnetwork-container
    image: "${DOCKER_REPO}/socialnetwork:${SN_ENV}-${SN_VERSION}"
    build:
      context: ../../../
      dockerfile: cicd/docker/setupDockerfile
      args:
        DOCKER_REPO: "${DOCKER_REPO}"
    volumes:
      - /media/:/media/
    ports:
    - 8000:8000
    tty: true

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${SN_DB}
      POSTGRES_USER: ${SN_USER}
      POSTGRES_PASSWORD: ${SN_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
